### ISSUE TITLE
Issue with adding text_categorizer pipe in spaCy's pipeline

### ISSUE THREAD

**Issue by bharatkoli14** [davidberenstein1957/spacy-setfit#5]
ValueError: [E002] Can't find factory for 'text_categorizer' for language English (en). This usually happens when 
spaCy calls `nlp.create_pipe` with a custom component name that's not registered on the current language class. If 
you're using a Transformer, make sure to install 'spacy-transformers'. If you're using a custom component, make 
sure you've added the decorator `@Language.component` (for function components) or `@Language.factory` (for class 
components).

Available factories: attribute_ruler, tok2vec, merge_noun_chunks, merge_entities, merge_subtokens, token_splitter, 
doc_cleaner, parser, beam_parser, lemmatizer, trainable_lemmatizer, entity_linker, ner, beam_ner, entity_ruler, 
tagger, morphologizer, senter, sentencizer, textcat, spancat, spancat_singlelabel, future_entity_ruler, span_ruler,
textcat_multilabel, en.lemmatizer

**Comment by davidberenstein1957** [comment]
Hi @bharatkoli14 , which version are you using?

**Comment by bharatkoli14** [comment]
spacy-setfit-0.1.4
spacy 3.5.3

**Comment by davidberenstein1957** [comment]
Could you share the code you use to produce this error? and also do a `pip list` with your dependencies?

**Comment by bharatkoli14** [comment]
Restarted the system..working now..  Thanks
