### ISSUE TITLE
spacy-setfit breaks classy-classification

### ISSUE THREAD

**Issue by joel-odlund** [davidberenstein1957/spacy-setfit#8]
I have both classy-classification and spacy-setfit installed. 

It seems like installing spacy-setfit actually breaks the classy-classification installation. 

When training a classy-classification pipeline,  the result is instead a setfit pipeline

I assume this has to do with both libraries using the default `text_categorizer` Spacy component. 
As far as I understand, since Spacy registers the components at install time,  you cannot have two components with the same name installed at the same time. 

To me, this is an issue since I need to evaluate several different model architectures in the same codebase.

**Comment by davidberenstein1957** [comment]
Thanks for the nudge. I managed to resolve this.
